markdown: GFM
baseurl: ""
url: "https://halfblood1223.github.io"
theme: rohanchandra/type-theme
  title: Type Theme
  avatar:
  gravatar:
  footer_text: Created by Yash Semlani
  email_address: yashveersemlan@gmail.com
  search: true
  	