markdown: GFM
title: "Yash Semlani's Site"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  blog:
    permalink: "/:collection/:path/"
    output: true
  cv:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    blog:
      # Give the collection a name
      name: Blog
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    cv:
      # Give the collection a name
      name: CV
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

